[2024-11-17 16:58:42] ERROR: [2g8v6] 请求错误: GET /api/captcha/generate?userId=12sadf 500 - 4ms 
ReferenceError: userId is not defined
    at CaptchaService.generateCode (/Users/tempest/tempest/code/captcha/src/services/captchaService.js:15:37)
    at CaptchaService.createCaptcha (/Users/tempest/tempest/code/captcha/src/services/captchaService.js:20:23)
    at generate (/Users/tempest/tempest/code/captcha/src/controllers/captchaController.js:15:33)
    at dispatch (/Users/tempest/tempest/code/captcha/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/tempest/tempest/code/captcha/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/tempest/tempest/code/captcha/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/tempest/tempest/code/captcha/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/tempest/tempest/code/captcha/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/tempest/tempest/code/captcha/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at module.exports (/Users/tempest/tempest/code/captcha/src/middleware/loggerMiddleware.js:12:15)
[2024-11-17 16:58:42] ERROR: 服务器错误 
ReferenceError: userId is not defined
    at CaptchaService.generateCode (/Users/tempest/tempest/code/captcha/src/services/captchaService.js:15:37)
    at CaptchaService.createCaptcha (/Users/tempest/tempest/code/captcha/src/services/captchaService.js:20:23)
    at generate (/Users/tempest/tempest/code/captcha/src/controllers/captchaController.js:15:33)
    at dispatch (/Users/tempest/tempest/code/captcha/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/tempest/tempest/code/captcha/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:423:16
    at dispatch (/Users/tempest/tempest/code/captcha/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /Users/tempest/tempest/code/captcha/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/Users/tempest/tempest/code/captcha/node_modules/.pnpm/koa-router@12.0.1/node_modules/koa-router/lib/router.js:428:31)
    at dispatch (/Users/tempest/tempest/code/captcha/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at module.exports (/Users/tempest/tempest/code/captcha/src/middleware/loggerMiddleware.js:12:15)
[2024-11-17 17:28:17] ERROR: 数据库连接失败: Access denied for user 'root'@'172.18.0.1' (using password: YES) 
SequelizeAccessDeniedError: Access denied for user 'root'@'172.18.0.1' (using password: YES)
    at ConnectionManager.connect (/Users/tempest/tempest/code/captcha/node_modules/.pnpm/sequelize@6.37.5_mysql2@3.11.4/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:94:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async ConnectionManager._connect (/Users/tempest/tempest/code/captcha/node_modules/.pnpm/sequelize@6.37.5_mysql2@3.11.4/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
    at async /Users/tempest/tempest/code/captcha/node_modules/.pnpm/sequelize@6.37.5_mysql2@3.11.4/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/Users/tempest/tempest/code/captcha/node_modules/.pnpm/sequelize@6.37.5_mysql2@3.11.4/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /Users/tempest/tempest/code/captcha/node_modules/.pnpm/sequelize@6.37.5_mysql2@3.11.4/node_modules/sequelize/lib/sequelize.js:305:26
    at async Sequelize.authenticate (/Users/tempest/tempest/code/captcha/node_modules/.pnpm/sequelize@6.37.5_mysql2@3.11.4/node_modules/sequelize/lib/sequelize.js:457:5)
[2024-11-17 17:28:21] ERROR: 数据库连接失败: Access denied for user 'root'@'172.18.0.1' (using password: YES) 
SequelizeAccessDeniedError: Access denied for user 'root'@'172.18.0.1' (using password: YES)
    at ConnectionManager.connect (/Users/tempest/tempest/code/captcha/node_modules/.pnpm/sequelize@6.37.5_mysql2@3.11.4/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:94:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async ConnectionManager._connect (/Users/tempest/tempest/code/captcha/node_modules/.pnpm/sequelize@6.37.5_mysql2@3.11.4/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
    at async /Users/tempest/tempest/code/captcha/node_modules/.pnpm/sequelize@6.37.5_mysql2@3.11.4/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/Users/tempest/tempest/code/captcha/node_modules/.pnpm/sequelize@6.37.5_mysql2@3.11.4/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /Users/tempest/tempest/code/captcha/node_modules/.pnpm/sequelize@6.37.5_mysql2@3.11.4/node_modules/sequelize/lib/sequelize.js:305:26
    at async Sequelize.authenticate (/Users/tempest/tempest/code/captcha/node_modules/.pnpm/sequelize@6.37.5_mysql2@3.11.4/node_modules/sequelize/lib/sequelize.js:457:5)
[2024-11-17 17:28:29] ERROR: 数据库连接失败: Access denied for user 'root'@'172.18.0.1' (using password: YES) 
SequelizeAccessDeniedError: Access denied for user 'root'@'172.18.0.1' (using password: YES)
    at ConnectionManager.connect (/Users/tempest/tempest/code/captcha/node_modules/.pnpm/sequelize@6.37.5_mysql2@3.11.4/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:94:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async ConnectionManager._connect (/Users/tempest/tempest/code/captcha/node_modules/.pnpm/sequelize@6.37.5_mysql2@3.11.4/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:222:24)
    at async /Users/tempest/tempest/code/captcha/node_modules/.pnpm/sequelize@6.37.5_mysql2@3.11.4/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:174:32
    at async ConnectionManager.getConnection (/Users/tempest/tempest/code/captcha/node_modules/.pnpm/sequelize@6.37.5_mysql2@3.11.4/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:197:7)
    at async /Users/tempest/tempest/code/captcha/node_modules/.pnpm/sequelize@6.37.5_mysql2@3.11.4/node_modules/sequelize/lib/sequelize.js:305:26
    at async Sequelize.authenticate (/Users/tempest/tempest/code/captcha/node_modules/.pnpm/sequelize@6.37.5_mysql2@3.11.4/node_modules/sequelize/lib/sequelize.js:457:5)
